environments:
    benrd: 
    kylerd:
    adamrd:
    marcusrd:
    ericrd:
    pondrd:
    #USING INT, MAIN AND SPRINT TO REFLECT OUR INTEGRATION (PR VERSION), MAIN (REFLECTING MAIN BRANCH), SPRINT (STATIC RELEASE VERSION FOR SPRINT REVIEW)
    int:
    main:
    sprint:
    prod-blue:
    prod-green: 
    prototype:
    dev:

releases:
# data-patterns
  - name: data-patterns-{{ .Environment.Name }}
    chart: ../helm/charts/data-patterns
    version: 0.0.1
    values:
      - overrides/data-patterns.yaml.gotmpl
    labels:
        category: dts
        app: data-patterns
        tier: frontend
    namespace: data-patterns-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false
