domain: red-desert-073d1c010.azurestaticapps.net      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://red-desert-073d1c010.azurestaticapps.net  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /