title: Data Patterns Library
title-fr: Bibliothèque de modèles de données
description: Reusable design patterns and components that give people more power over their data and help teams build more trustworthy digital services.
domain: dts-stn.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://dts-stn.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /Data-Patterns
adobe-analytics: //assets.adobedtm.com/be5dfd287373/0127575cd23a/launch-913b1beddf7a-staging.min.js # Staging

exclude: [node_modules, .gitignore, .markdown-link-check.json, .makrdownlint.json, .travis.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, link-check.js, package-lock.json, package.json, README.md, SECURITY.md, Dockerfile, Gemfile, Gemfile.lock, helm, helmfile]

collections:
  patterns:
    output: true
