domain: datapatterns-dev.bdm-dev.dts-stn.com     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://datapatterns-dev.bdm-dev.dts-stn.com  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /
