{{- if .Values.rbac.enabled -}}
{{- $fullName := include "fullname" . -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ .Values.rbac.azureAdGroupId }}
roleRef:
  kind: Role
  name: {{ $fullName }}
  apiGroup: ""
{{- end }}
