import Head from 'next/head';
import {GCFooter, GCHeader} from 'gc-tortilla';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Data Patterns Library</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GCHeader/>
            <h1>Hello World!</h1>
            <GCFooter/>
        </div>
    )
}
