import fs from "fs";
import path from "path";
import Head from 'next/head';
import ReactMarkdown from 'react-markdown';
import matter from "gray-matter";
import {GCFooter, GCHeader} from 'gc-tortilla';

export default function Pattern(props) {

    return (
        <div>
            <Head>
                <title>{props.pattern.data.name}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <GCHeader/>
            <h1>{props.pattern.data.name}</h1>
            <p>{props.pattern.data["short-description"]}</p>
            <ReactMarkdown children={props.pattern.markdown}/>
            <div>Date Modified {props.pattern.data["date-modified"]}</div>
            <GCFooter/>
        </div>
    )
}

export async function getStaticPaths() {
    const files = fs.readdirSync("content/en/patterns");
    console.log("files: ", files);
    const paths = files.map(filename => ({
        params: {
            slug: filename.replace(".md", "")
        }
    }));
    console.log("paths: ", paths);

    return {
        paths,
        fallback: false
    };
}

export async function getStaticProps({ params: { slug } }) {
    const markdownWithMetadata = fs.readFileSync(path.join("content/en/patterns", slug + ".md")).toString();

    const parsedMarkdown = matter(markdownWithMetadata);

    return {
        props: {
            pattern: {
                markdown: parsedMarkdown.content,
                data: parsedMarkdown.data
            }
        }
    };
  }