import Head from 'next/head';
import ReactMarkdown from 'react-markdown';
import ContentContainer from '../organisms/ContentContainer';
import styles from '../../styles/Home.module.css';

export default function Home(props) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Data Patterns Library</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ContentContainer>
                <ReactMarkdown children={props.content.markdown}/>
            </ContentContainer>
        </div>
    )
}
