import Head from 'next/head';
import styles from '../../styles/Home.module.css';

export default function Home(props) {
    return (
        <main>
            <Head>
                <title>Data Patterns Library</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Data Patterns Library</h1>
        </main>
    );
}
