name: Build Container and Push Latest

on: workflow_dispatch

jobs:
  build_docker_push:
    runs-on: ubuntu-latest
    name: Build Docker and Push
    env:
      IMAGE: dpl-bmd
      BDM_REGISTRY: esdcdpsbdmk8sprototypeacr.azurecr.io
#      MTS_REGISTRY: mtscontainers.azurecr.io
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      # uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.7.2

    # Standard usage
    - name: Jekyll Build
      run: |
        bundle install
        bundle exec jekyll build JEKYLL_ENV=prod --config _config.yml,_config_prod.yml
        
    - name: LS
      run: ls -al ./_site/*

#    - name: Login to MTS
#      uses: docker/login-action@v1 
#      with:
#        registry: ${{ github.MTS_REGISTRY }}
#        username: ${{ secrets.AZURE_GITHUB_SPN_ID }}
#        password: ${{ secrets.AZURE_GITHUB_SPN_PASS }}

#    - name: Manual Docker
#      run: |
#        docker build -t ${{ github.MTS_REGISTRY }}/${{ github.IMAGE }}:latest  .
#        docker tag ${{ github.MTS_REGISTRY }}/${{ github.IMAGE }}:latest ${{ github.MTS_REGISTRY }}/${{ github.IMAGE }}:${{ github.run_number }}
#        docker push ${{ github.MTS_REGISTRY }}/${{ github.IMAGE }}:${{ github.run_number }}
        
    - name: Login to BDM
      uses: docker/login-action@v1 
      with:
        registry: esdcdpsbdmk8sprototypeacr.azurecr.io
        username: ${{ secrets.AZURE_GITHUB_SPN_ID }}
        password: ${{ secrets.AZURE_GITHUB_SPN_PASS }}
        
    - name: Manual Docker
      run: |
        docker build -t ${{ github.BDM_REGISTRY }}/${{ github.IMAGE }}:latest  .
        docker tag ${{ github.BDM_REGISTRY }}/${{ github.IMAGE }}:latest  ${{ github.BDM_REGISTRY }}/${{ github.IMAGE }}:${{ github.run_number }} 
        docker push ${{ github.BDM_REGISTRY }}/${{ github.IMAGE }} -a 
